name: Test frontend-wsl
on:
  pull_request:
    branches:
      - master
             
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t mahenderkb6/react-test -f Dockerfile.dev .
      - run: docker run -e CI=true mahenderkb6/react-test npm run test